### ISSUE TITLE
How to build on linux

### ISSUE THREAD

**Issue by Geequlim** [editorconfig/editorconfig-qtcreator#2]
I can't build from source on arch linux

```bash
$ mkdir build && cd build
$ qmake ../editorconfig.pro 
Cannot read /src/qtcreatorplugin.pri: No such file or directory
```

**Comment by hgraeber** [comment]
As the README.MD already states, you need a source and build tree for your distribution and let the QTC_SOURCE and QTC_BUILD environment variables contain their paths. That usually means to compile qtcreator yourself.

Fortunately for linux the qtcreator package already contains a proper build tree, so `QTC_BINARY=/usr` suffices for the build tree and arch linux has a package containing the source tree. With this one installed `QTC_SOURCE=/usr/src/qtcreator` should be fine for the source tree.

After setting those variables you can build the plugin as described above.

**Comment by Geequlim** [comment]
Thanks!
