### ISSUE TITLE
Build for QtCreator 4.6.0 windows

### ISSUE THREAD

**Issue by xlazom00** [editorconfig/editorconfig-qtcreator#5]
Build for QtCreator 4.5.2 windows plz

**Comment by hgraeber** [comment]
The Plugin built for 4.5.0 works for 4.5.2, too.

Maybe the QtCreator version number of the zip files shall be 4.5 or 4.5.x...

**Comment by xlazom00** [comment]
sorry I missed that we have 4.6.0 already :)
so plz build for 4.6.0

**Comment by hgraeber** [comment]
Done.

**Comment by xlazom00** [comment]
thx
